--Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
--1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
--By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

--sum_of_fib n
--  | n >= 2 = fib n + sum_of_fib(n - 1)
--  | n == 1 = fib n

--fib n
--  | n == 1 = 1
--  | n == 2 = 2
--  | otherwise = fib(n - 1) + fib(n - 2)

fib_1 n i n1 n2 acc
    | i > n = acc
    | i == 1 = fib_1 n (i + 1) n1 n2 (acc + n1)
    | i == 2 = fib_1 n (i + 1) n1 n2 (acc + n2)
    | otherwise = fib_1 n (i + 1) n2 sum (acc + sum)
    where sum = n1 + n2

main = print (fib_1 50000 1 1 2 0)
